2020-09-30 16:09:51,498 - 20992 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\table_creation.py", line 15, in create_table\n    sqlfile = open(file_path,\'r\')\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\balaji.a.arunachalam\\\\PycharmProjects\\\\Back_end(Python,SQL)\\\\src\\\\main\\\\table_creation.py.sql'\n"]
2020-09-30 16:09:51,498 - 20992 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\table_creation.py", line 15, in create_table\n    sqlfile = open(file_path,\'r\')\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\balaji.a.arunachalam\\\\PycharmProjects\\\\Back_end(Python,SQL)\\\\src\\\\main\\\\table_creation.py.sql'\n"]
2020-09-30 16:09:51,498 - 20992 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\table_creation.py", line 15, in create_table\n    sqlfile = open(file_path,\'r\')\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\balaji.a.arunachalam\\\\PycharmProjects\\\\Back_end(Python,SQL)\\\\src\\\\main\\\\table_creation.py.sql'\n"]
