2020-09-30 17:05:45,315 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\1_category_details.csv.csv'\n"]
2020-09-30 17:05:45,315 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\1_category_details.csv.csv'\n"]
2020-09-30 17:05:45,315 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\1_category_details.csv.csv'\n"]
2020-09-30 17:05:45,380 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\2_customer_details.csv.csv'\n"]
2020-09-30 17:05:45,380 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\2_customer_details.csv.csv'\n"]
2020-09-30 17:05:45,380 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\2_customer_details.csv.csv'\n"]
2020-09-30 17:05:45,380 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\2_customer_details.csv.csv'\n"]
2020-09-30 17:05:45,380 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\2_customer_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,419 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\3_order_status_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,459 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\4_seller_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,499 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\5_cart_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,539 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\6_customer_address_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,580 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\7_order_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,620 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\8_product_stock_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,661 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.0_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,701 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.1_cart_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,742 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.2_category_product_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,782 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.3_customer_rating_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,821 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.4_invoice_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,863 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.5_payment_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,904 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.6_product_ordered_details.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
2020-09-30 17:05:45,945 - 29684 DEBUG - ['Traceback (most recent call last):\n', '  File "C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src/main/insertion.py", line 34, in record_insertion\n    with open(file_path, \'r\') as read_file:\n', "FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/balaji.a.arunachalam/PycharmProjects/Back_end(Python,SQL)/src\\\\files\\\\records\\\\9.7_shipping_status.csv.csv'\n"]
