2020-10-05 09:59:57,018 - 33948 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\ddl_commands.py", line 37, in rename_table\n    self.obj.executes(command)\n', "AttributeError: 'Dev' object has no attribute 'executes'\n"]
2020-10-05 09:59:57,018 - 33948 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\ddl_commands.py", line 37, in rename_table\n    self.obj.executes(command)\n', "AttributeError: 'Dev' object has no attribute 'executes'\n"]
2020-10-05 09:59:57,018 - 33948 DEBUG - ['Traceback (most recent call last):\n', '  File "C:\\Users\\balaji.a.arunachalam\\PycharmProjects\\Back_end(Python,SQL)\\src\\main\\ddl_commands.py", line 37, in rename_table\n    self.obj.executes(command)\n', "AttributeError: 'Dev' object has no attribute 'executes'\n"]
